### ISSUE TITLE
Question/documentation: what does MDK stand for?

### ISSUE THREAD

**Issue by mokus0** [NordicSemiconductor/nrfx#68]
It's used all over and I know what it _does_ but I can't find an explanation of why it's called "mdk" (which might be helpful in documenting my own build rules, to explain at point of use why it's being pulled in)

**Comment by adfernandes** [comment]
Really? I always thought it was `Middleware Development Kit` since "middleware" is usually the Hardware Abstraction Layer (HAL) plus a bit of driver abstraction over the "raw register" access level...

I think that [Microcontroller Development Kit](http://www2.keil.com/mdk5/) refers to Keil's IDE product, not the "middleware" of Nordic's software in this repo.

**Comment by kl-cruz** [comment]
Hi,
@inductivekickback You are right, It is Microcontroller Development Kit. You can read more at: https://www.nordicsemi.com/Software-and-tools/Development-Tools/nRF-MDK

**Comment by adfernandes** [comment]
Darn. Another good theory ruined by facts! 😉
